common: &default_settings
  key: <%= ENV['ATHENA_KEY'] %>
  secret: <%= ENV['ATHENA_SECRET'] %>
  version: <%= ENV['ATHENA_VERSION'] %>
  practice_id: <%= ENV['ATHENA_PRACTICE_ID'] %>

development:
  <<: *default_settings

test:
  <<: *default_settings

develop:
  <<: *default_settings

production:
  <<: *default_settings
