months:
  1:
  - name: New Year's Day
    regions: []
    mday: 1
    observed: to_weekday_if_weekend(date)
  5:
  - name: Memorial Day
    week: -1
    regions: []
    wday: 1
  7:
  - name: Independence Day
    regions: []
    mday: 4
    observed: to_weekday_if_weekend(date)
  9:
  - name: Labor Day
    week: 1
    regions: []
    wday: 1
  11:
  - name: Thanksgiving
    week: 4
    regions: []
    wday: 4
  12:
  - name: Christmas Day
    regions: []
    mday: 25
    observed: to_weekday_if_weekend(date)
